// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Expense struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Note   string `json:"note"`
	Amount string `json:"amount"`
	Title  string `json:"title"`
	Date   string `json:"date"`
	Status string `json:"status"`
}

type Mutation struct {
}

type NewExpense struct {
	UserID string `json:"userId"`
	Note   string `json:"note"`
	Amount string `json:"amount"`
	Title  string `json:"title"`
	Date   string `json:"date"`
	Status string `json:"status"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
